
name: 'salesforce_formula_udfs'
version: '0.1.0'
config-version: 2

macro-paths: ["udfs"]

# All UDF macros will be executed as such on the on-run-start config
on-run-start:
  - "{{ salesforce_formula_udfs.cast_as_string() }}"
  - "{{ salesforce_formula_udfs.cast_as_integer() }}"

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"